package com.newgen.custom.rakbank.resources.concrete;
//gaurav-s created static demo response strings
public class DemoResponse {
	public String getentitydetailresponse(){
		String response= "<EE_EAI_MESSAGE xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">"+
			"   <EE_EAI_HEADER>"+
			"      <MsgFormat>ENTITY_DETAILS</MsgFormat>"+
			"      <MsgVersion>0000</MsgVersion>"+
			"      <RequestorChannelId>CAS</RequestorChannelId>"+
			"      <RequestorUserId>RAKUSER</RequestorUserId>"+
			"      <RequestorLanguage>E</RequestorLanguage>"+
			"      <RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
			"      <ReturnCode>0000</ReturnCode>"+
			"      <ReturnDesc>Successful</ReturnDesc>"+
			"      <MessageId>ENTITY_DETAILS_0002</MessageId>"+
			"      <Extra1>REP||SHELL.JOHN</Extra1>"+
			"      <Extra2>2016-10-23T12:03:29.109+04:00</Extra2>"+
			"   </EE_EAI_HEADER>"+
			"   <EntityDetailsRes>"+
			"      <BankId>RAK</BankId>"+
			"      <Acid>0180213644003</Acid>"+
			"      <LinkedAccount>0003224979001</LinkedAccount>"+
			"      <AccountStatus>001</AccountStatus>"+
			"      <AccountCategory>SINGLY</AccountCategory>"+
			"      <JointAccIndicator>Y</JointAccIndicator>"+
			"      <SchemeCode>AZRP1</SchemeCode>"+
			"      <SchemeType>ODA</SchemeType>"+
			"      <PrimaryCIF>"+
			"         <CIFID>0358464</CIFID>"+
			"         <CustomerType>N</CustomerType>"+
			"         <CustomerSegment>PBD</CustomerSegment>"+
			"         <CustomerSubSeg>PBN</CustomerSubSeg>"+
			"         <CustomerName>ACCOUNT NAME FOR  0358464</CustomerName>"+
			"         <CustomerCategory>PBN</CustomerCategory>"+
			"         <CustomerStatus>ACTVE</CustomerStatus>"+
			"         <CustomerMobileNumber>00971501896783</CustomerMobileNumber>"+
			"         <AddressLine1>LONDON rtret5y568678678768 97897898987987789  5678</AddressLine1>"+
			"         <AddressLine2>GOLDEN rtret5y568678678768 97897898987987789  5678</AddressLine2>"+
			"         <AddressLine3>GOLDEN rtret5y568678678768 97897898987987789  5678</AddressLine3>"+
			"         <AddressLine4>COPPER</AddressLine4>"+
			"         <CityCode>Dubai</CityCode>"+
			"         <CountryCode>UAE</CountryCode>"+
			"         <PrimaryEmailId>123456789123@RAKBANK.AE</PrimaryEmailId>"+
			"         <DOB>1900-01-01</DOB>"+
			"         <Nationality>LK</Nationality>"+
			"         <LinkedDebitCardNumber>5239266465706009</LinkedDebitCardNumber>"+
			"         <FinacleRelation>Y</FinacleRelation>"+
			"         <IsStaff>N</IsStaff>"+
			"         <YearsSinceInUAE> DD-MM-YYYY</YearsSinceInUAE>"+
			"         <ResidentCountry> AE</ResidentCountry>"+
			"         <NoOfDependents>1</NoOfDependents>"+
			"         <FatcaDet>"+
			"            <USRelation>O</USRelation>"+
			"            <TIN>121222</TIN>"+
			"            <FatcaReason></FatcaReason>"+
			"            <DocumentsCollected>ID DOC!SELF-ATTEST FORM</DocumentsCollected>"+
			"            <SignedDate> DD-MM-YYYY</SignedDate>"+
			"            <SignedExpiryDate> DD-MM-YYYY</SignedExpiryDate>"+
			"         </FatcaDet>"+
			"         <OECDDet>"+
			"            <CityOfBirth></CityOfBirth>"+
			"            <CountryOfBirth></CountryOfBirth>"+
			"            <CRSUnDocFlg>Y</CRSUnDocFlg>"+
			"            <CRSUndocFlgReason></CRSUndocFlgReason>"+
			"            <ReporCntryDet>"+
			"               <CntryOfTaxRes></CntryOfTaxRes>"+
			"               <TINNumber></TINNumber>"+
			"               <NoTINReason></NoTINReason>"+
			"               <MiscellaneousID></MiscellaneousID>"+
			"            </ReporCntryDet>"+
			"         </OECDDet>"+
			"      </PrimaryCIF>"+
			"   </EntityDetailsRes>"+
			"</EE_EAI_MESSAGE>";
		return response;
}


	public String getcustomereligiblityresponse(){
		String response="<EE_EAI_MESSAGE>"+
				"	<EE_EAI_HEADER>"+
				"		<MsgFormat>CUSTOMER_ELIGIBILITY</MsgFormat>"+
				"		<MsgVersion>0001</MsgVersion>"+
				"		<RequestorChannelId>CAS</RequestorChannelId>"+
				"		<RequestorUserId> RAKUSER </RequestorUserId>"+
				"		<RequestorLanguage>E</RequestorLanguage>"+
				"		<RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"		<ReturnCode>0000</ReturnCode>"+
				"		<ReturnDesc>Successful</ReturnDesc>"+
				"		<MessageId>DEDUPLIST0012</MessageId>"+
				"		<Extra1>REP||BPM.123</Extra1>"+
				"		<Extra2>2016-07-12T05:17:43.449+04:00</Extra2>"+
				"	</EE_EAI_HEADER>"+
				"	<CustomerEligibilityResponse>"+
				"		<BankId>RAK</BankId>"+
				"		<CustomerDetails>"+
				"			<SearchType>Internal</SearchType>"+
				"			<CustId>1111</CustId>"+
				"			<PassportNum>AHJ8786</PassportNum>"+
				"			<BlacklistFlag>Y</BlacklistFlag>"+
				"			<BlacklistReasonCode/>"+
				"			<BlacklistDate>2017-05-19</BlacklistDate>"+
				"			<DuplicationFlag>Y</DuplicationFlag>"+
				"			<AcctCustFlag>Y</AcctCustFlag>"+
				"			<NegatedFlag>N</NegatedFlag>"+
				"			<NegatedReasonCode>Code</NegatedReasonCode>"+
				"			<NegatedDate>2017-05-19</NegatedDate>"+
				"			<Products>"+
				"				<ProductType>CAPS</ProductType>"+
				"				<NoOfProducts>1</NoOfProducts>"+
				"			</Products>"+
				"			<Products>"+
				"				<ProductType>RLS</ProductType>"+
				"				<NoOfProducts>2</NoOfProducts>"+
				"			</Products>"+
				"		</CustomerDetails>"+
				"		<CustomerDetails>"+
				"			<SearchType>Internal</SearchType>"+
				"			<CustId>2222</CustId>"+
				"			<PassportNum>AHJ8786</PassportNum>"+
				"			<BlacklistFlag>Y</BlacklistFlag>"+
				"			<BlacklistReasonCode/>"+
				"			<BlacklistDate>2017-05-19</BlacklistDate>"+
				"			<DuplicationFlag>Y</DuplicationFlag>"+
				"			<AcctCustFlag>Y</AcctCustFlag>"+
				"			<NegatedFlag>N</NegatedFlag>"+
				"			<NegatedReasonCode>Code</NegatedReasonCode>"+
				"			<NegatedDate>2017-05-19</NegatedDate>"+
				"			<Products>"+
				"				<ProductType>CAPS</ProductType>"+
				"				<NoOfProducts>1</NoOfProducts>"+
				"			</Products>"+
				"			<Products>"+
				"				<ProductType>RLS</ProductType>"+
				"				<NoOfProducts>2</NoOfProducts>"+
				"			</Products>"+
				"		</CustomerDetails>"+
				"		<CustomerDetails>"+
				"			<SearchType>External</SearchType>"+
				"			<CustId>1234</CustId>"+
				"             <BlacklistFlag>Y</BlacklistFlag>"+
				"			<BlacklistReasonCode/>"+
				"			<BlacklistDate>2017-05-19</BlacklistDate>"+
				"		</CustomerDetails>"+
				"		<CustomerDetails>"+
				"			<SearchType>External</SearchType>"+
				"			<CustId>4567</CustId>  "+
				"              		<BlacklistFlag>Y</BlacklistFlag>"+
				"			<BlacklistReasonCode/>"+
				"			<BlacklistDate>2017-05-19</BlacklistDate>"+
				"		</CustomerDetails>"+
				"	</CustomerEligibilityResponse>"+
				"</EE_EAI_MESSAGE>"; 
		return response;
}

	public String getcustomerdetailresponse(){
		String response="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"+
				"<EE_EAI_MESSAGE>"+
				"	<EE_EAI_HEADER>"+
				"		<MsgFormat>CUSTOMER_DETAILS</MsgFormat>"+
				"		<MsgVersion>0000</MsgVersion>"+
				"		<RequestorChannelId>CAS</RequestorChannelId>"+
				"		<RequestorUserId>RAKUSER</RequestorUserId>"+
				"		<RequestorLanguage>E</RequestorLanguage>"+
				"		<RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"		<ReturnCode>0000</ReturnCode>"+
				"		<ReturnDesc>Success</ReturnDesc>"+
				"		<MessageId>123123453</MessageId>"+
				"		<Extra1>REP||JOHN.JOHN</Extra1>"+
				"		<Extra2>2008-01-16T18:28:00.000+04:00</Extra2>"+
				"	</EE_EAI_HEADER>"+
				"<FetchCustomerDetailsRes>"+
				"		<BankId>RAK</BankId>"+
				"		<CIFDet>"+
				"			<CIFID>0712700</CIFID>"+
				"			<RetCorpFlag>R</RetCorpFlag>"+
				"			<CifType>EB</CifType>"+
				"			<CustomerStatus>ACTVE</CustomerStatus>"+
				"			<CustomerSegment>PBD</CustomerSegment>"+
				"			<CustomerSubSeg>PBN</CustomerSubSeg>"+
				"			<GrossSalary>12345</GrossSalary>"+
				"			<SalaryTranflag>Y</SalaryTranflag>"+
				"			<TotHouseholdInc>12345</TotHouseholdInc>"+
				"			<Commissions>13</Commissions>"+
				"			<PhnDet>"+
				"				<PhnType>CELLPH1</PhnType>"+
				"				<PhnPrefFlag>Y</PhnPrefFlag>"+
				"				<PhnCountryCode>*****</PhnCountryCode>"+
				"				<PhnCityCode>****</PhnCityCode>"+
				"				<PhnLocalCode>*********</PhnLocalCode>"+
				"				<PhoneNo>**************</PhoneNo>"+
				"			</PhnDet>"+
				"			<AddrDet>"+
				"				<AddressType>Permanent</AddressType>"+
				"				<EffectiveFrom>07-10-2010</EffectiveFrom>"+
				"				<EffectiveTo>31-12-2099</EffectiveTo>"+
				"				<HoldMailFlag>N</HoldMailFlag>"+
				"				<HoldMailBCName>xxxxxx</HoldMailBCName> "+
				"				<HoldMailReason>aaaaaaaaaaaaaa</HoldMailReason> "+
				"				<ReturnFlag>N</ReturnFlag>"+
				"				<AddrPrefFlag>N</AddrPrefFlag>"+
				"				<AddrLine1>324</AddrLine1>"+
				"				<AddrLine2>bangalore</AddrLine2>"+
				"				<AddrLine3>haryana</AddrLine3>"+
				"				<AddrLine4>Delhi</AddrLine4>"+
				"				<POBox>*****</POBox>"+
				"				<zipcode></zipcode>"+
				"				<City>***</City>"+
				"				<State>Delhi1</State>"+
				"				<Country>AE</Country>"+
				"				<Years>2</Years>"+
				"			</AddrDet>"+
				"			<AddrDet>"+
				"				<AddressType>Temporary</AddressType>"+
				"				<EffectiveFrom>07-10-2010</EffectiveFrom>"+
				"				<EffectiveTo>31-12-2099</EffectiveTo>"+
				"				<HoldMailFlag>N</HoldMailFlag>"+
				"				<ReturnFlag>N</ReturnFlag>"+
				"				<AddrPrefFlag>N</AddrPrefFlag>"+
				"				<AddrLine1>Noida</AddrLine1>"+
				"				<AddrLine2>Barakhamba Road</AddrLine2>"+
				"				<AddrLine3>Near shani Mandir</AddrLine3>"+
				"				<AddrLine4>234</AddrLine4>"+
				"				<POBox>*****</POBox>"+
				"				<zipcode></zipcode>"+
				"				<City>***</City>"+
				"				<State>Delhi1</State>"+
				"				<Country>AE</Country>"+
				"				<Years>2</Years>"+
				"			</AddrDet>"+
				"			<EmlDet>"+
				"				<EmlType>ELML1</EmlType>"+
				"				<EmlPrefFlag>Y</EmlPrefFlag>"+
				"				<Email>************************</Email>"+
				"			</EmlDet>"+
				"			<EmlDet>"+
				"				<EmlType>ELML2</EmlType>"+
				"				<EmlPrefFlag>N</EmlPrefFlag>"+
				"				<Email>************************</Email>"+
				"			</EmlDet>"+
				"			<isPremium>Y</isPremium>"+
				"			<isWMCustomer>N</isWMCustomer>"+
				"			<DocDet>"+
				"				<DocType>VISA</DocType>"+
				"				<DocTypeDesc>VISA FILE Number</DocTypeDesc>"+
				"				<DocIsVerified>Y</DocIsVerified>	"+
				"				<DocNo>324378438432</DocNo>"+
				"				<DocExpDate>20-12-2016</DocExpDate>"+
				"			</DocDet>"+
				"			<DocDet>"+
				"				<DocType>EMID</DocType>"+
				"				<DocTypeDesc>Emirates Id</DocTypeDesc>"+
				"				<DocIsVerified>Y</DocIsVerified>	"+
				"				<DocNo>784198546081476</DocNo>"+
				"				<DocExpDate>29-12-2016</DocExpDate>"+
				"			</DocDet>"+
				"			<DocDet>"+
				"				<DocType>Passport</DocType>"+
				"				<DocTypeDesc>PassportDesc</DocTypeDesc>"+
				"				<DocIsVerified>Y</DocIsVerified>	"+
				"				<DocNo>1234</DocNo>"+
				"				<DocExpDate>17-12-2016</DocExpDate>"+
				"			</DocDet>"+
				"			<BuddyRMDetails>"+
				"				<BuddyRMName>Ganesh</BuddyRMName>"+
				"				<BuddyRMPhone>971122456789</BuddyRMPhone>"+
				"				<BuddyRMEmail>Ganesh@rak.com</BuddyRMEmail>				"+
				"			</BuddyRMDetails>"+
				"			<BackupRMDetails>"+
				"				<RMName>Suresh</RMName>"+
				"				<RMPhone>971123456789</RMPhone>"+
				"				<RMEmail>Suresh@rak.com</RMEmail>"+
				"			</BackupRMDetails>"+
				"			<RetAddnlDet>"+
				"				<Title>Mr.</Title>"+
				"				<CustomerName>Vikas Bansal</CustomerName>"+
				"				<FName>Vikas</FName>"+
				"				<MName>Kumar</MName>"+
				"				<LName>Bansal</LName>"+
				"				<Gender>F</Gender>"+
				"				<DOB>28-01-1986</DOB>"+
				"				<MinorFlg>N</MinorFlg>"+
				"				<MaritialStatus>W</MaritialStatus>"+
				"				<MotherMaidenName>MOTHERS MAIDEN NAME</MotherMaidenName>"+
				"				<Nationality>IN</Nationality>"+
				"				<ResidentCountry>AE</ResidentCountry>"+
				"				<IDIssueDate>25/5/1996</IDIssueDate>"+
				"				<Resident>Y</Resident>"+
				"				<SecondNationality>Indian</SecondNationality>"+
				"				<GCCNationality>N</GCCNationality>"+
				"				<CustCategory>VIP</CustCategory>"+
				"				<YearsUAE>2</YearsUAE>"+
				"				<EmirateResidence>ABU DHABI</EmirateResidence>"+
				"				<EmirateVisa>Yes</EmirateVisa>"+
				"				<VIPFlag>Y</VIPFlag>"+
				"			</RetAddnlDet>"+
				"		</CIFDet>"+
				"		<CIFDet>"+
				"			<CIFID>0712701</CIFID>"+
				"			<RetCorpFlag>C</RetCorpFlag>"+
				"			<CifType>EB</CifType>"+
				"			<CustomerStatus>ACTVE</CustomerStatus>"+
				"			<CustomerSegment>CBD</CustomerSegment>"+
				"			<CustomerSubSeg>CBN</CustomerSubSeg>"+
				"			<PhnDet>"+
				"				<PhnType>CELLPH1</PhnType>"+
				"				<PhnPrefFlag>Y</PhnPrefFlag>"+
				"				<PhnCountryCode>*****</PhnCountryCode>"+
				"				<PhnLocalCode>*********</PhnLocalCode>"+
				"				<PhoneNo>**************</PhoneNo>"+
				"			</PhnDet>"+
				"			<AddrDet>"+
				"				<AddressType>Permanent</AddressType>"+
				"				<EffectiveFrom>07-10-2010</EffectiveFrom>"+
				"				<EffectiveTo>31-12-2099</EffectiveTo>"+
				"				<HoldMailFlag>N</HoldMailFlag>"+
				"				<ReturnFlag>N</ReturnFlag>"+
				"				<AddrPrefFlag>N</AddrPrefFlag>"+
				"				<AddrLine1>121</AddrLine1>"+
				"				<AddrLine2>Near metro stn</AddrLine2>"+
				"				<AddrLine3>Noida</AddrLine3>"+
				"				<AddrLine4>Maharaj marg</AddrLine4>"+
				"				<POBox>Delhi</POBox>"+
				"				<zipcode></zipcode>"+
				"				<City>***</City>"+
				"				<State>Delhi1</State>"+
				"				<Country>AE</Country>"+
				"				<Years>2</Years>"+
				"			</AddrDet>"+
				"			<AddrDet>"+
				"				<AddressType>Temporary</AddressType>"+
				"				<EffectiveFrom>07-10-2010</EffectiveFrom>"+
				"				<EffectiveTo>31-12-2099</EffectiveTo>"+
				"				<HoldMailFlag>N</HoldMailFlag>"+
				"				<ReturnFlag>N</ReturnFlag>"+
				"				<AddrPrefFlag>N</AddrPrefFlag>"+
				"				<AddrLine1>456</AddrLine1>"+
				"				<AddrLine2>221</AddrLine2>"+
				"				<AddrLine3>187</AddrLine3>"+
				"				<AddrLine4>954</AddrLine4>"+
				"				<POBox>*****</POBox>"+
				"				<zipcode></zipcode>"+
				"				<City>***</City>"+
				"				<State>Delhi1</State>"+
				"				<Country>AE</Country>"+
				"				<Years>2</Years>"+
				"			</AddrDet>"+
				"			<EmlDet>"+
				"				<EmlType>ELML1</EmlType>"+
				"				<EmlPrefFlag>Y</EmlPrefFlag>"+
				"				<Email>************************</Email>"+
				"			</EmlDet>"+
				"			<EmlDet>"+
				"				<EmlType>ELML2</EmlType>"+
				"				<EmlPrefFlag>N</EmlPrefFlag>"+
				"				<Email>************************</Email>"+
				"			</EmlDet>"+
				"			<isPremium>Y</isPremium>"+
				"			<isWMCustomer>N</isWMCustomer>"+
				"			<DocDet>"+
				"				<DocType>VISA</DocType>"+
				"				<DocTypeDesc>VISA FILE Number</DocTypeDesc>"+
				"				<DocIsVerified>Y</DocIsVerified>"+
				"				<DocNo>324378438432</DocNo>"+
				"				<DocExpDate>19-12-2016</DocExpDate>"+
				"			</DocDet>"+
				"			<DocDet>"+
				"				<DocType>EMID</DocType>"+
				"				<DocTypeDesc>Emirates Id</DocTypeDesc>"+
				"				<DocIsVerified>Y</DocIsVerified>	"+
				"				<DocNo>784198546081476</DocNo>"+
				"				<DocExpDate>29-12-2016</DocExpDate>"+
				"			</DocDet>"+
				"				<DocDet>"+
				"				<DocType>Passport</DocType>"+
				"				<DocTypeDesc>PassportDesc</DocTypeDesc>"+
				"				<DocIsVerified>Y</DocIsVerified>	"+
				"				<DocNo>1234</DocNo>"+
				"				<DocExpDate>17-12-2016</DocExpDate>"+
				"			</DocDet>"+
				"			<BuddyRMDetails>"+
				"				<BuddyRMName>Ganesh</BuddyRMName>"+
				"				<BuddyRMPhone>971122456789</BuddyRMPhone>"+
				"				<BuddyRMEmail>Ganesh@rak.com</BuddyRMEmail>"+
				"			</BuddyRMDetails>"+
				"			<BackupRMDetails>"+
				"				<RMName>Suresh</RMName>"+
				"				<RMPhone>971123456789</RMPhone>"+
				"				<RMEmail>Suresh@rak.com</RMEmail>"+
				"			</BackupRMDetails>"+
				"			<CorpAddnlDet>"+
				"				<CorpName>Infosys LLC</CorpName>"+
				"				<BusinessIncDate>28-01-1986</BusinessIncDate>"+
				"				<OrgCountry>N</OrgCountry>"+
				"				<LegEnt>Partnership</LegEnt>"+
				"				<CreditTurnover>102034</CreditTurnover>"+
				"				<CustId>12345</CustId>"+
				"				<Name></Name>"+
				"				<PassportNo></PassportNo>"+
				"				<Nationality></Nationality>"+
				"				<shareHolderPercentage></shareHolderPercentage>"+
				"			</CorpAddnlDet>"+
				"			<EmpDet>"+
				"				<EmpType>Salaried</EmpType>"+
				"				<EmployerCode>E</EmployerCode>"+
				"				<EmployerName>Abhinav</EmployerName>"+
				"				<EmpStatus>S</EmpStatus>"+
				"				<DOJ>20-2-2000</DOJ>"+
				"				<Designation>Software Engineer</Designation>"+
				"				<EffectiveFrom>2-1-2001</EffectiveFrom>"+
				"			</EmpDet>"+
				"			<ReporCntryDet>"+
				"				<CntryOfTaxRes>324</CntryOfTaxRes>"+
				"				<TINNumber>43243</TINNumber>"+
				"				<NoTINReason>vfd</NoTINReason>"+
				"				<MiscellaneousID>dfds</MiscellaneousID>"+
				"			</ReporCntryDet>"+
				"			<DealInfo>		"+
				"				<DealCount>3</DealCount>"+
				"				<DealInfoDet>"+
				"					<ProdType>A</ProdType>"+
				"					<DealDesc>CREDIT CARD.</DealDesc>"+
				"					<DealId>D12321</DealId>"+
				"					<Identifier>B</Identifier>"+
				"					<ContextType>LGIN</ContextType>"+
				"					<DealStartDate>2015-11-16</DealStartDate>"+
				"					<DealExpiryDate>2008-11-18</DealExpiryDate>"+
				"				</DealInfoDet>"+
				"			</DealInfo>"+
				"			<PartnerDet>"+
				"				<CustId></CustId>"+
				"				<Name>fhgfhg</Name>"+
				"				<PassportNo>123098</PassportNo>"+
				"				<Nationality>Indian</Nationality>"+
				"				<shareHolderPercentage></shareHolderPercentage>"+
				"			</PartnerDet>"+
				"			<KYCDet>"+
				"				<KYCHeld>vgvfd</KYCHeld>"+
				"				<KYCReviewDate>5-6-2000</KYCReviewDate>"+
				"			</KYCDet>"+
				"			<OECDDet>"+
				"				<CityOfBirth>hjgghj</CityOfBirth>"+
				"				<CountryOfBirth>fgfhg</CountryOfBirth>"+
				"				<CRSUnDocFlg>hjgjh</CRSUnDocFlg>"+
				"				<CRSUndocFlgReason>ggjgj</CRSUndocFlgReason>"+
				"			</OECDDet>"+
				"			<FatcaDet>"+
				"				<USRelation>Y</USRelation>"+
				"				<TIN>12</TIN>"+
				"				<FatcaReason>dfds</FatcaReason>"+
				"				<DocumentsCollected>dfds</DocumentsCollected>"+
				"				<SignedDate>23-5-2000</SignedDate>"+
				"				<SignedExpiryDate>25-5-2003</SignedExpiryDate>"+
				"			</FatcaDet>"+
				"		</CIFDet>"+
				"		</FetchCustomerDetailsRes>"+
				"	</EE_EAI_MESSAGE>	";
		return response;
}
 
	public String getgenerateotpresponse(){
		String response="<EE_EAI_MESSAGE>"+
				"   <EE_EAI_HEADER>"+
				"      	<MsgFormat>OTP_MANAGEMENT</MsgFormat>"+
				"      	<MsgVersion>0000</MsgVersion>"+
				"	<RequestorChannelId>CAS</RequestorChannelId>"+
				"      	<RequestorUserId>RAKUSER</RequestorUserId>"+
				"      	<RequestorLanguage>E</RequestorLanguage>"+
				"      	<RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"      	<ReturnCode>0000</ReturnCode>"+
				"      	<ReturnDesc>Successful</ReturnDesc>"+
				"      	<MessageId>123123453</MessageId>"+
				"      	<Extra1>REP||TEST.JOHN</Extra1>"+
				"      	<Extra2>1900-01-01T00:00:00.000+04:00</Extra2>"+
				"   </EE_EAI_HEADER>"+
				"   <ManageOTP>"+
				"	<BankId>RAK</BankId>"+
				"	<ServiceType>CardlessWithdrawal</ServiceType>"+
				"	<RequestType>GenerateOTP</RequestType>"+
				"	<RequestRefNo>MOB14234</RequestRefNo>"+
				"	<OTPReferenceNo>123234234534535</OTPReferenceNo>"+
				"	<CustomerName>John</CustomerName>"+
				"	<CustomerMobileNo>00971501234567</CustomerMobileNo>"+
				"<OTP>1221</OTP>"+
				"	<OTPGeneratedDateTime>2014-01-01T00:00:00.000+04:00</OTPGeneratedDateTime></ManageOTP></EE_EAI_MESSAGE>";
		return response;
}
	public String getvalidateotpresponse(){
		String response="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"+
				"<EE_EAI_MESSAGE>"+
				"	<EE_EAI_HEADER>"+
				"		<MsgFormat> OTP_SUMMARY </MsgFormat>"+
				"		<MsgVersion>0000</MsgVersion>"+
				"		<RequestorChannelId>CAS</RequestorChannelId>"+
				"		<RequestorUserId>RAKUSER</RequestorUserId>"+
				"		<RequestorLanguage>E</RequestorLanguage>"+
				"		<RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"		<ReturnCode>0000</ReturnCode>"+
				"		<ReturnDesc>Success</ReturnDesc>"+
				"		<MessageId>123123453</MessageId>"+
				"		<Extra1>REP||LAXMANRET.LAXMANRET</Extra1>"+
				"		<Extra2>2008-01-16T18:28:00.000+04:00</Extra2>"+
				"	</EE_EAI_HEADER>"+
				"	<Transactions>"+
				"		<BankId>RAK</BankId>"+
				"        <ServiceType>CardlessWithdrawal</ServiceType>"+
				"        <RequestType>InquireOTP</RequestType>"+
				"		<CustType>C</CustType>"+
				"		<CIFID>0300300</CIFID>"+
				"		<RelatedCIF>3258966</RelatedCIF>"+
				"		<NextPageKey></NextPageKey>"+
				"		<TransactionDetail>"+
				"			<ActType>A</ActType>"+
				"			<AcctID>0029279355050</AcctID>"+
				"			<ConsumerName>xxxxx</ConsumerName>"+
				"			<ConsumerNumber>xxxxxx</ConsumerNumber>"+
				"			<OTPGeneratedDateTime>2014-01-01T00:00:00.000+04:00</OTPGeneratedDateTime>"+
				"			<OTPExpiryDateTime >2014-01-01T00:00:00.000+04:00</OTPExpiryDateTime >"+
				"			<OTPLastStatusUpdatedDateTime>2014-01-01T00:00:00.000+04:00</OTPLastStatusUpdatedDateTime>"+
				"			<OTPReferenceNo></OTPReferenceNo>"+
				"			<TxnAmt>100.00</TxnAmt>"+
				"			<OTPStatus>Active</OTPStatus>"+
				"			<TxnCrn>AED</TxnCrn>"+
				"			<RequestRefNo>45345345</RequestRefNo>                  "+
				"		</TransactionDetail>"+
				"		<TransactionDetail>"+
				"			<ConsumerName>xxxxx</ConsumerName>"+
				"			<ConsumerNumber>xxxxxx</ConsumerNumber>"+
				"			<OTPGeneratedDateTime>2014-01-01T00:00:00.000+04:00</OTPGeneratedDateTime>"+
				"			<OTPExpiryDateTime >2014-01-01T00:00:00.000+04:00</OTPExpiryDateTime >"+
				"			<OTPLastStatusUpdatedDateTime>2014-01-01T00:00:00.000+04:00</OTPLastStatusUpdatedDateTime>"+
				"			<OTPReferenceNo></OTPReferenceNo>"+
				"			<TxnAmt>100.00</TxnAmt>"+
				"			<OTPStatus>Active</OTPStatus>"+
				"			<TxnCrn>AED</TxnCrn>"+
				"			<RequestRefNo>45345345</RequestRefNo>                  "+
				"		</TransactionDetail>"+
				"	</Transactions>		"+
				"</EE_EAI_MESSAGE>";
		return response;
}
	
	public String getgenuinecheck(){
		String response="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"+
				"<EE_EAI_MESSAGE>"+
				"   <EE_EAI_HEADER>"+
				"      <MsgFormat>EID_Genuine</MsgFormat>"+
				"      <MsgVersion>0001</MsgVersion>"+
				"      <RequestorChannelId>BPM</RequestorChannelId>"+
				"      <RequestorUserId>BPMUSER</RequestorUserId>"+
				"      <RequestorLanguage>E</RequestorLanguage>"+
				"      <RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"      <ReturnCode>0000</ReturnCode>"+
				"      <ReturnDesc>Successful</ReturnDesc>"+
				"      <MessageId>DEDUPLIST0012</MessageId>"+
				"      <Extra1>REP||BPM.123</Extra1>"+
				"      <Extra2>2016-07-12T05:17:43.449+04:00</Extra2>"+
				"   </EE_EAI_HEADER>"+
				"   <EIDA_Genuine_Response>"+
				"      <StatusCode>S</StatusCode>"+
				"		<StatusDesc>SUCCESS</StatusDesc>"+
				"   </EIDA_Genuine_Response>"+
				"</EE_EAI_MESSAGE>";
		return response;
}
	public String getnewcustomercheck(){
		String response="<EE_EAI_MESSAGE>"+
				"   <EE_EAI_HEADER>"+
				"      <MsgFormat>NEW_CUSTOMER_REQ</MsgFormat>"+
				"      <MsgVersion>0001</MsgVersion>"+
				"      <RequestorChannelId>RBD</RequestorChannelId>"+
				"      <RequestorUserId>RBDUSER</RequestorUserId>"+
				"      <RequestorLanguage>E</RequestorLanguage>"+
				"      <RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"      <ReturnCode>0000</ReturnCode>"+
				"      <ReturnDesc>Success</ReturnDesc>"+
				"      <MessageId>UTCFUNDBLOCK002</MessageId>"+
				"      <Extra1>REP||RBD.123</Extra1>"+
				"      <Extra2>2014-03-25T11:05:30.000+04:00</Extra2>"+
				"   </EE_EAI_HEADER>"+
				"   <NewCustomerResponse>"+
				"      <BankId>RAK</BankId> "+
				"      <CIFId>1234567</CIFId>"+
				"      <Desc>Corporate CIF</Desc>"+
				"      <Entity>Customer</Entity>"+
				"      <Service>Corporate CIF Creation</Service>"+
				"      <Status>Active</Status>"+
				"   </NewCustomerResponse>"+
				"</EE_EAI_MESSAGE>";
		return response;
}
	
	public String getnewaccount(){
		String response="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"+
				"<EE_EAI_MESSAGE> "+
				"<EE_EAI_HEADER> "+
				"<MsgFormat>NEW_ACCOUNT_REQ</MsgFormat> "+
				"<MsgVersion>0001</MsgVersion> "+
				"<RequestorChannelId>EBC.INB</RequestorChannelId> "+
				"<RequestorUserId>RAKUSER</RequestorUserId> "+
				"<RequestorLanguage>E</RequestorLanguage> "+
				"<RequestorSecurityInfo>secure</RequestorSecurityInfo> "+
				"<ReturnCode>000</ReturnCode> "+
				"<ReturnDesc>Success</ReturnDesc> "+
				"<MessageId>123123453</MessageId> "+
				"<Extra1>REP||SHELL.JOHN</Extra1> "+
				"<Extra2>YYYY-MM-DDThh:mm:ss.mmm+hh:mm</Extra2> "+
				"</EE_EAI_HEADER> "+
				"<AcccountResponse> "+
				"<BankId>RAK</BankId> "+
				"<BranchId>003</BranchId> "+
				"<CustomerId>1221342</CustomerId> "+
				"<CurrencyCode>AED</CurrencyCode> "+
				"<EligibilityStatus>Y</EligibilityStatus> "+
				"<EligibilityStatusCode>Y</EligibilityStatusCode> "+
				"<EligibilityStatusDesc>Y</EligibilityStatusDesc> "+
				"<NewAcid>0001100002102</NewAcid>"+
				"<IBANNumber>0001987654321400</IBANNumber>"+
				"<FirstName>John</FirstName> <MidName>Fredrick</MidName><LastName>Mathews</LastName><DocType>PPT</DocType><DocRefNum>T5777G66</DocRefNum> <MotherMaidenName>LISA</MotherMaidenName><AcctStat>A</AcctStat><AcctSchemeCode>ACNP</AcctSchemeCode> "+
				"<AcctSchemeType>SBA</AcctSchemeType> "+
				"</AcccountResponse> "+
				"</EE_EAI_MESSAGE>";
		return response;
}
	
	public String getaccountsummary(){
		String response="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"+
				"<EE_EAI_MESSAGE>"+
				"	<EE_EAI_HEADER>"+
				"		<MsgFormat> ACCOUNT_SUMMARY</MsgFormat>"+
				"		<MsgVersion>0000</MsgVersion>"+
				"		<RequestorChannelId>CAS</RequestorChannelId>"+
				"		<RequestorUserId>RAKUSER</RequestorUserId>"+
				"		<RequestorLanguage>E</RequestorLanguage>"+
				"		<RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"		<ReturnCode>0000</ReturnCode>"+
				"		<ReturnDesc>Success</ReturnDesc>"+
				"		<MessageId>123123453</MessageId>"+
				"		<Extra1>REP||JOHN.JOHN</Extra1>"+
				"		<Extra2>2008-01-16T18:28:00.000+04:00</Extra2>"+
				"	</EE_EAI_HEADER>"+
				"	<FetchIBSAccountListRes>"+
				"		<CIFID>263401</CIFID>"+
				"		<BankId>RAK</BankId>"+
				"		<ProdProc>FINACLECORE,CAPS,RLS</ProdProc>"+
				"		<StatusAsOf> 1900-01-01T00:00:00.000+04:00</StatusAsOf>"+
				"		<IsIslamic>I/C/B</IsIslamic>"+
				"		<IBSAccountDetail>"+
				"			<BranchId>0001</BranchId>"+
				"			<Acid>0123456789012</Acid>"+
				"			<Foracid>0001987654321400</Foracid>"+
				"			<AcctType>TDA</AcctType>"+
				"			<AccountCategory>TA001</AccountCategory>"+
				"			<CrnCode>AED</CrnCode>"+
				"			<NicName>Shankar</NicName>"+
				"			<AccountName>Shankar</AccountName>"+
				"			<LocDesc></LocDesc>"+
				"			<AcctBal>1022</AcctBal>"+
				"			<CurrentBal>1234</CurrentBal>"+
				"<Interest>0.1</Interest>"+
				"<LoanAmount>0</LoanAmount>"+
				"<LoanAmtInAED>0</LoanAmtInAED >"+
				"<DepositAmtInAED>0</DepositAmtInAED >"+
				"<AutoRenFlag>N</AutoRenFlag>"+
				"<JntAcctIndicator>N</JntAcctIndicator>"+
				"			<AcctStatus>001</AcctStatus>"+
				"			<AcctAccess></AcctAccess>"+
				"			<AcctOpnDt>2006-01-30</AcctOpnDt>"+
				"			<MaturityDt>1900-01-01</MaturityDt>"+
				"			<IntRate>12.00</IntRate>"+
				"			<MaturityAmt>1200</MaturityAmt>"+
				"			<ProductId>CURRENT ACCOUNT</ProductId>"+
				"			<ModeOfOperation>SINGLY</ModeOfOperation>"+
				"<ApplicantType></ApplicantType>"+
				"		</IBSAccountDetail>	"+
				"	</FetchIBSAccountListRes>"+
				"</EE_EAI_MESSAGE>";
		return response;
}
	
	public String getfinancialsummary(){
		String response=	"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"+
				"<EE_EAI_MESSAGE>"+
				"   <EE_EAI_HEADER>"+
				"      <MsgFormat>FINANCIAL_SUMMARY</MsgFormat>"+
				"      <MsgVersion>0000</MsgVersion>"+
				"      <RequestorChannelId>CAS</RequestorChannelId>"+
				"      <RequestorUserId>RAKUSER</RequestorUserId>"+
				"      <RequestorLanguage>E</RequestorLanguage>"+
				"      <RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"      <ReturnCode>0000</ReturnCode>"+
				"      <ReturnDesc>Success</ReturnDesc>"+
				"      <MessageId>123123453</MessageId>"+
				"      <Extra1>REP||JOHN.JOHN</Extra1>"+
				"      <Extra2>2008-01-16T18:28:00.000+04:00</Extra2>"+
				"   </EE_EAI_HEADER>"+
				"   <FinancialSummaryRes>"+
				"      <BankId>RAK</BankId>"+
				"      <CIFID>263401</CIFID>"+
				"      <AcctId>1000000001</AcctId>"+
				"      <OperationType>1</OperationType>"+
				"      <OperationDesc>Salary Details</OperationDesc>"+
				"      <SalTxnDetails>"+
				"         <SalCreditDate>12</SalCreditDate>"+
				"         <Amount>100</Amount>"+
				"      </SalTxnDetails>"+
				"      <CashDepositDtls>"+
				"         <TotalCashDepAmt>100</TotalCashDepAmt>"+
				"      </CashDepositDtls>"+
				"      <AvgBalanceDtls>"+
				"         <Month>12</Month>"+
				"         <AvgBalance>100</AvgBalance>"+
				"      </AvgBalanceDtls>"+
				"      <ReturnsDtls>"+
				"         <ReturnType>DDS</ReturnType>"+
				"         <ReturnNumber>1223</ReturnNumber>"+
				"         <ReturnAmount>100</ReturnAmount>"+
				"         <RetReasonCode>1223</RetReasonCode>"+
				"         <ReturnDate>1223</ReturnDate>"+
				"      </ReturnsDtls>"+
				"      <LienDetails>"+
				"         <LienId>100</LienId>"+
				"         <LienAmount>100</LienAmount>"+
				"         <LienRemarks>abcd</LienRemarks>"+
				"         <LienReasonCode>100</LienReasonCode>"+
				"         <LienStartDate>100</LienStartDate>"+
				"         <LienExpDate>100</LienExpDate>"+
				"      </LienDetails>"+
				"   </FinancialSummaryRes>"+
				"</EE_EAI_MESSAGE>";

		return response;
}
	public String getcustomerexposure(){
		String response="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"+
				"<EE_EAI_MESSAGE>"+
				"   <EE_EAI_HEADER>"+
				"      <MsgFormat>CUSTOMER_EXPOSURE</MsgFormat>"+
				"      <MsgVersion>0001</MsgVersion>"+
				"      <RequestorChannelId>CAS</RequestorChannelId>"+
				"      <RequestorUserId>RAKUSER</RequestorUserId>"+
				"      <RequestorLanguage>E</RequestorLanguage>"+
				"      <RequestorSecurityInfo>secure</RequestorSecurityInfo>"+
				"      <ReturnCode>0000</ReturnCode>"+
				"      <ReturnDesc>Success</ReturnDesc>"+
				"      <MessageId>123123453</MessageId>"+
				"      <Extra1>REQ||SHELL.JOHN</Extra1>"+
				"      <Extra2>YYYY-MM-DDThh:mm:ss.mmm+hh:mm</Extra2>"+
				"   </EE_EAI_HEADER>"+
				"   <CustomerExposureResponse>"+
				"      <RequestType>ExternalExposure</RequestType>"+
				"      <ExposureDetails>"+
				"         <IsDirect>N</IsDirect>"+
				"         <CustInfo>"+
				"            <CustId>"+
				"               <CustIdType>CIF Id</CustIdType>"+
				"               <CustIdValue>asd12</CustIdValue>"+
				"            </CustId>"+
				"            <FullNm>asd12</FullNm>"+
				"            <BirthDt>1967-08-13</BirthDt>"+
				"            <Gender>1</Gender>"+
				"            <CustSegment>asd12</CustSegment>"+
				"            <CustSubSegment>asd12</CustSubSegment>"+
				"            <RMName>asd12</RMName>"+
				"            <TotalOutstanding>0.0</TotalOutstanding>"+
				"            <TotalOverdue>0.0</TotalOverdue>"+
				"            <TotalExposure>0.0</TotalExposure>"+
				"            <NoOfContracts>0</NoOfContracts>"+
				"            <CreditGrade>String</CreditGrade>"+
				"         </CustInfo>"+
				"         <RecordDestributions>"+
				"            <RecordDestribution>"+
				"               <ContractType>TotalSummary</ContractType>"+
				"               <Contract_Role_Type/>"+
				"               <TotalNo>48</TotalNo>"+
				"               <DataProvidersNo>11</DataProvidersNo>"+
				"               <RequestNo>39</RequestNo>"+
				"               <DeclinedNo>0</DeclinedNo>"+
				"               <RejectedNo>0</RejectedNo>"+
				"               <NotTakenUpNo>0</NotTakenUpNo>"+
				"               <ActiveNo>9</ActiveNo>"+
				"               <ClosedNo>0</ClosedNo>"+
				"            </RecordDestribution>"+
				"            <RecordDestribution>"+
				"               <ContractType>Installments</ContractType>"+
				"               <Contract_Role_Type>Holder</Contract_Role_Type>"+
				"               <TotalNo>24</TotalNo>"+
				"               <DataProvidersNo>1</DataProvidersNo>"+
				"               <RequestNo>23</RequestNo>"+
				"               <DeclinedNo>0</DeclinedNo>"+
				"               <RejectedNo>0</RejectedNo>"+
				"               <NotTakenUpNo>0</NotTakenUpNo>"+
				"               <ActiveNo>1</ActiveNo>"+
				"               <ClosedNo>0</ClosedNo>"+
				"            </RecordDestribution>"+
				"            <RecordDestribution>"+
				"               <ContractType>NotInstallments</ContractType>"+
				"               <Contract_Role_Type>Holder</Contract_Role_Type>"+
				"               <TotalNo>0</TotalNo>"+
				"               <DataProvidersNo>0</DataProvidersNo>"+
				"               <RequestNo>0</RequestNo>"+
				"               <DeclinedNo>0</DeclinedNo>"+
				"               <RejectedNo>0</RejectedNo>"+
				"               <NotTakenUpNo>0</NotTakenUpNo>"+
				"               <ActiveNo>0</ActiveNo>"+
				"               <ClosedNo>0</ClosedNo>"+
				"            </RecordDestribution>"+
				"            <RecordDestribution>"+
				"               <ContractType>CreditCards</ContractType>"+
				"               <Contract_Role_Type>Holder</Contract_Role_Type>"+
				"               <TotalNo>23</TotalNo>"+
				"               <DataProvidersNo>1</DataProvidersNo>"+
				"               <RequestNo>16</RequestNo>"+
				"               <DeclinedNo>0</DeclinedNo>"+
				"               <RejectedNo>0</RejectedNo>"+
				"               <NotTakenUpNo>0</NotTakenUpNo>"+
				"               <ActiveNo>7</ActiveNo>"+
				"               <ClosedNo>0</ClosedNo>"+
				"            </RecordDestribution>"+
				"            <RecordDestribution>"+
				"               <ContractType>Services</ContractType>"+
				"               <Contract_Role_Type>Holder</Contract_Role_Type>"+
				"               <TotalNo>1</TotalNo>"+
				"               <DataProvidersNo>1</DataProvidersNo>"+
				"               <RequestNo>0</RequestNo>"+
				"               <DeclinedNo>0</DeclinedNo>"+
				"               <RejectedNo>0</RejectedNo>"+
				"               <NotTakenUpNo>0</NotTakenUpNo>"+
				"               <ActiveNo>1</ActiveNo>"+
				"               <ClosedNo>0</ClosedNo>"+
				"            </RecordDestribution>"+
				"         </RecordDestributions>"+
				"         <Derived>"+
				"            <Total_Exposure>0</Total_Exposure>"+
				"            <Oldest_Contract_Start_Date>2009-11-19T00:00:00</Oldest_Contract_Start_Date>"+
				"            <WorstCurrentPaymentDelay>0</WorstCurrentPaymentDelay>"+
				"            <Worst_PaymentDelay_Last24Months>0</Worst_PaymentDelay_Last24Months>"+
				"            <Worst_Status_Last24Months>0</Worst_Status_Last24Months>"+
				"            <Nof_Records>0</Nof_Records>"+
				"            <NoOf_Cheque_Return_Last3>0</NoOf_Cheque_Return_Last3>"+
				"            <Nof_DDES_Return_Last3Months>0</Nof_DDES_Return_Last3Months>"+
				"            <Nof_Cheque_Return_Last6>0</Nof_Cheque_Return_Last6>"+
				"            <DPD30_Last6Months>0</DPD30_Last6Months>"+
				"            <Nof_Enq_Last90Days>0</Nof_Enq_Last90Days>"+
				"            <Nof_Enq_Last60Days>0</Nof_Enq_Last60Days>"+
				"            <Nof_Enq_Last30Days>0</Nof_Enq_Last30Days>"+
				"            <Internal_WriteOff_Check>asd12</Internal_WriteOff_Check>"+
				"         </Derived>"+
				"         <ProductExposureDetails>"+
				"            <ChequeDetails>"+
				"               <ChqType>BounceCheque</ChqType>"+
				"               <Number>11225</Number>"+
				"               <Amount>99999</Amount>"+
				"               <ReturnDate>2014-11-30</ReturnDate>"+
				"               <ProviderNo>B13</ProviderNo>"+
				"               <Type>Bounced Cheques</Type>"+
				"               <ReasonCode>Insufficient Funds</ReasonCode>"+
				"               <Severity>Multiple</Severity>"+
				"            </ChequeDetails>"+
				"            <ChequeDetails>"+
				"               <ChqType>BounceCheque</ChqType>"+
				"               <Number>11225</Number>"+
				"               <Amount>99999</Amount>"+
				"               <ReturnDate>2014-11-30</ReturnDate>"+
				"               <ProviderNo>B13</ProviderNo>"+
				"               <Type>Bounced Cheques</Type>"+
				"               <ReasonCode>Insufficient Funds</ReasonCode>"+
				"               <Severity>Multiple</Severity>"+
				"            </ChequeDetails>"+
				"            <LoanDetails>"+
				"               <AgreementId>asd12</AgreementId>"+
				"               <LoanStat>asd12</LoanStat>"+
				"               <LoanType>asd12</LoanType>"+
				"               <CustRoleType>1</CustRoleType>"+
				"               <TotalNoOfInstalments>12</TotalNoOfInstalments>"+
				"               <RemainingInstalments>5</RemainingInstalments>"+
				"               <Bucket>0.0</Bucket>"+
				"               <KeyDt>"+
				"                  <KeyDtType>StartDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>CloseDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>LastUpdDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <CurCode>AED</CurCode>"+
				"               <AmountDtls>"+
				"                  <AmtType>OutStandingBalance</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>TotalAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>PaymentsAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>CreditLimit</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>OverdueAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <PaymentMode>0.0</PaymentMode>"+
				"               <WriteoffStat>asd12asd12</WriteoffStat>"+
				"               <WriteoffStatDt>1967-08-13</WriteoffStatDt>"+
				"               <NofDaysPmtDelay>12</NofDaysPmtDelay>"+
				"               <MaxDaysPmtDelay>2</MaxDaysPmtDelay>"+
				"               <MaxDaysPmtDelayDt>1967-08-13</MaxDaysPmtDelayDt>"+
				"               <MonthsOnBook>2</MonthsOnBook>"+
				"               <LastRepmtDt>1967-08-13</LastRepmtDt>"+
				"               <DisputeAlert>N</DisputeAlert>"+
				"               <NonActivePmt>Y</NonActivePmt>"+
				"               <IsCurrent>Y</IsCurrent>"+
				"               <ExternalWriteOffCheck>a</ExternalWriteOffCheck>"+
				"               <AECBHistMonthCnt>5</AECBHistMonthCnt>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD30_Last6Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD60_Last18Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"            </LoanDetails>"+
				"            <LoanDetails>"+
				"               <AgreementId>asd12</AgreementId>"+
				"               <LoanStat>asd12</LoanStat>"+
				"               <LoanType>asd12</LoanType>"+
				"               <CustRoleType>1</CustRoleType>"+
				"               <TotalNoOfInstalments>12</TotalNoOfInstalments>"+
				"               <RemainingInstalments>5</RemainingInstalments>"+
				"               <Bucket>0.0</Bucket>"+
				"               <KeyDt>"+
				"                  <KeyDtType>StartDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>CloseDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>LastUpdDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <CurCode>AED</CurCode>"+
				"               <AmountDtls>"+
				"                  <AmtType>OutStandingBalance</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>TotalAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>PaymentsAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>CreditLimit</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>OverdueAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"              <CollectionsCode></CollectionsCode>"+
				"             <PreviousLoanDBR></PreviousLoanDBR>"+
				"              <PreviousLoanTAI></PreviousLoanTAI>"+
				"             <PreviousLoanMultiple></PreviousLoanMultiple>"+
				"             <PreviousLoanEmp></PreviousLoanEmp>"+
				"            <CurrentlyCurrentFlg></CurrentlyCurrentFlg>"+
				"            <MarketingCode></MarketingCode>"+
				"            <PartSettlementDetails>"+
				"<SettlementDate></SettlementDate>"+
				"<SettlementAmount></SettlementAmount>"+
				"<SettlementReason></Settlement Reason>"+
				"</PartSettlementDetails>"+
				"<NoOfDaysInPipeline></NoOfDaysInPipeline>"+
				"               <PaymentMode>0.0</PaymentMode>"+
				"               <WriteoffStat>asd12asd12</WriteoffStat>"+
				"               <WriteoffStatDt>1967-08-13</WriteoffStatDt>"+
				"               <NofDaysPmtDelay>12</NofDaysPmtDelay>"+
				"               <MaxDaysPmtDelay>2</MaxDaysPmtDelay>"+
				"               <MaxDaysPmtDelayDt>1967-08-13</MaxDaysPmtDelayDt>"+
				"               <MonthsOnBook>2</MonthsOnBook>"+
				"               <LastRepmtDt>1967-08-13</LastRepmtDt>"+
				"               <DisputeAlert>N</DisputeAlert>"+
				"               <NonActivePmt>Y</NonActivePmt>"+
				"               <IsCurrent>Y</IsCurrent>"+
				"               <ExternalWriteOffCheck>a</ExternalWriteOffCheck>"+
				"               <AECBHistMonthCnt>5</AECBHistMonthCnt>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD30_Last6Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD60_Last18Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"            </LoanDetails>"+
				"            <CardDetails>"+
				"               <CardEmbossNum>1234</CardEmbossNum>"+
				"               <CardStatus>Active</CardStatus>"+
				"               <CardType>Primary</CardType>"+
				"               <CustRoleType>1</CustRoleType>"+
				"               <KeyDt>"+
				"                  <KeyDtType>StartDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>CloseDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>LastUpdDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <CurCode>AED</CurCode>"+
				"               <AmountDtls>"+
				"                  <AmtType>OutStandingBalance</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>TotalAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>PaymentsAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>CreditLimit</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>OverdueAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <PaymentMode>0.0</PaymentMode>"+
				"               <WriteoffStat>asd12asd12</WriteoffStat>"+
				"               <WriteoffStatDt>1967-08-13</WriteoffStatDt>"+
				"               <NofDaysPmtDelay>12</NofDaysPmtDelay>"+
				"               <MaxDaysPmtDelay>2</MaxDaysPmtDelay>"+
				"               <MaxDaysPmtDelayDt>1967-08-13</MaxDaysPmtDelayDt>"+
				"               <MonthsOnBook>2</MonthsOnBook>"+
				"               <LastRepmtDt>1967-08-13</LastRepmtDt>"+
				"               <IsDuplicate>Y</IsDuplicate>"+
				"               <DisputeAlert>a</DisputeAlert>"+
				"               <NonActivePmt>a</NonActivePmt>"+
				"               <IsCurrent>Y</IsCurrent>"+
				"               <CurUtilRate>10</CurUtilRate>"+
				"               <ExternalWriteOffCheck>a</ExternalWriteOffCheck>"+
				"               <AECBHistMonthCnt>5</AECBHistMonthCnt>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD30_Last6Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD60_Last18Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"            </CardDetails>"+
				"            <CardDetails>"+
				"               <CardEmbossNum>1234</CardEmbossNum>"+
				"               <CardStatus>Active</CardStatus>"+
				"               <CardType>Primary</CardType>"+
				"               <CustRoleType>1</CustRoleType>"+
				"               <KeyDt>"+
				"                  <KeyDtType>StartDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>CloseDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>LastUpdDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <CurCode>AED</CurCode>"+
				"               <AmountDtls>"+
				"                  <AmtType>OutStandingBalance</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>TotalAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>PaymentsAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>CreditLimit</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>OverdueAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <PaymentMode>0.0</PaymentMode>"+
				"               <WriteoffStat>asd12asd12</WriteoffStat>"+
				"               <WriteoffStatDt>1967-08-13</WriteoffStatDt>"+
				"               <NofDaysPmtDelay>12</NofDaysPmtDelay>"+
				"               <MaxDaysPmtDelay>2</MaxDaysPmtDelay>"+
				"               <MaxDaysPmtDelayDt>1967-08-13</MaxDaysPmtDelayDt>"+
				"               <MonthsOnBook>2</MonthsOnBook>"+
				"               <LastRepmtDt>1967-08-13</LastRepmtDt>"+
				"               <IsDuplicate>Y</IsDuplicate>"+
				"               <DisputeAlert>a</DisputeAlert>"+
				"               <NonActivePmt>a</NonActivePmt>"+
				"               <IsCurrent>Y</IsCurrent>"+
				"               <CurUtilRate>10</CurUtilRate>"+
				"               <ExternalWriteOffCheck>a</ExternalWriteOffCheck>"+
				"               <AECBHistMonthCnt>5</AECBHistMonthCnt>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD30_Last6Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD60_Last18Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"            </CardDetails>"+
				"            <AcctDetails>"+
				"               <AcctId>asd12</AcctId>"+
				"               <AcctStat>Active</AcctStat>"+
				"               <AcctCur>AED</AcctCur>"+
				"               <AcctNm>asd12</AcctNm>"+
				"               <AcctType>asd12</AcctType>"+
				"               <CustRoleType>1</CustRoleType>"+
				"               <KeyDt>"+
				"                  <KeyDtType>StartDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>CloseDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>LastUpdDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <AmountDtls>"+
				"                  <AmtType>OutStandingBalance</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>TotalAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>PaymentsAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>CreditLimit</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>OverdueAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <PaymentMode>0.0</PaymentMode>"+
				"               <WriteoffStat>asd12asd12</WriteoffStat>"+
				"               <WriteoffStatDt>1967-08-13</WriteoffStatDt>"+
				"               <NofDaysPmtDelay>12</NofDaysPmtDelay>"+
				"               <MaxDaysPmtDelay>2</MaxDaysPmtDelay>"+
				"               <MaxDaysPmtDelayDt>1967-08-13</MaxDaysPmtDelayDt>"+
				"               <MonthsOnBook>2</MonthsOnBook>"+
				"               <LastRepmtDt>1967-08-13</LastRepmtDt>"+
				"               <IsDuplicate>Y</IsDuplicate>"+
				"               <DisputeAlert>a</DisputeAlert>"+
				"               <NonActivePmt>a</NonActivePmt>"+
				"               <IsCurrent>Y</IsCurrent>"+
				"               <CurUtilRate>10</CurUtilRate>"+
				"               <ExternalWriteOffCheck>a</ExternalWriteOffCheck>"+
				"               <AECBHistMonthCnt>5</AECBHistMonthCnt>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD30_Last6Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD60_Last18Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"            </AcctDetails>"+
				"            <AcctDetails>"+
				"               <AcctId>asd12</AcctId>"+
				"               <AcctStat>Active</AcctStat>"+
				"               <AcctCur>AED</AcctCur>"+
				"               <AcctNm>asd12</AcctNm>"+
				"               <AcctType>asd12</AcctType>"+
				"               <CustRoleType>1</CustRoleType>"+
				"               <KeyDt>"+
				"                  <KeyDtType>StartDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>CloseDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>LastUpdDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <AmountDtls>"+
				"                  <AmtType>OutStandingBalance</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>TotalAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>PaymentsAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>CreditLimit</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>OverdueAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <PaymentMode>0.0</PaymentMode>"+
				"               <WriteoffStat>asd12asd12</WriteoffStat>"+
				"               <WriteoffStatDt>1967-08-13</WriteoffStatDt>"+
				"               <NofDaysPmtDelay>12</NofDaysPmtDelay>"+
				"               <MaxDaysPmtDelay>2</MaxDaysPmtDelay>"+
				"               <MaxDaysPmtDelayDt>1967-08-13</MaxDaysPmtDelayDt>"+
				"               <MonthsOnBook>2</MonthsOnBook>"+
				"               <LastRepmtDt>1967-08-13</LastRepmtDt>"+
				"               <IsDuplicate>Y</IsDuplicate>"+
				"               <DisputeAlert>a</DisputeAlert>"+
				"               <NonActivePmt>a</NonActivePmt>"+
				"               <IsCurrent>Y</IsCurrent>"+
				"               <CurUtilRate>10</CurUtilRate>"+
				"               <ExternalWriteOffCheck>a</ExternalWriteOffCheck>"+
				"               <AECBHistMonthCnt>5</AECBHistMonthCnt>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD30_Last6Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"               <DelinquencyInfo>"+
				"                  <BucketType>DPD60_Last18Months</BucketType>"+
				"                  <BucketValue>2</BucketValue>"+
				"               </DelinquencyInfo>"+
				"            </AcctDetails>"+
				"            <ServicesDetails>"+
				"               <ProviderNo>String</ProviderNo>"+
				"               <ServiceType>asd12</ServiceType>"+
				"               <ServiceStat>Active</ServiceStat>"+
				"               <ServiceName>asd12</ServiceName>"+
				"               <CustRoleType>1</CustRoleType>"+
				"               <KeyDt>"+
				"                  <KeyDtType>StartDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>CloseDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>LastUpdDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <CurCode>AED</CurCode>"+
				"               <AmountDtls>"+
				"                  <AmtType>OutStandingBalance</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>TotalAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>PaymentsAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>OverdueAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <PaymentMode>0.0</PaymentMode>"+
				"               <WriteoffStat>asd12asd12</WriteoffStat>"+
				"               <WriteoffStatDt>1967-08-13</WriteoffStatDt>"+
				"               <MaxDaysPmtDelay>2</MaxDaysPmtDelay>"+
				"               <MaxDaysPmtDelayDt>1967-08-13</MaxDaysPmtDelayDt>"+
				"               <MonthsOnBook>2</MonthsOnBook>"+
				"               <LastRepmtDt>1967-08-13</LastRepmtDt>"+
				"               <DisputeAlert>a</DisputeAlert>"+
				"               <NonActivePmt>a</NonActivePmt>"+
				"               <IsCurrent>Y</IsCurrent>"+
				"               <ExternalWriteOffCheck>a</ExternalWriteOffCheck>"+
				"               <AECBHistMonthCnt>5</AECBHistMonthCnt>"+
				"            </ServicesDetails>"+
				"            <ServicesDetails>"+
				"               <ProviderNo>String</ProviderNo>"+
				"               <ServiceType>asd12</ServiceType>"+
				"               <ServiceStat>Active</ServiceStat>"+
				"               <ServiceName>asd12</ServiceName>"+
				"               <CustRoleType>1</CustRoleType>"+
				"               <KeyDt>"+
				"                  <KeyDtType>StartDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>CloseDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <KeyDt>"+
				"                  <KeyDtType>LastUpdDt</KeyDtType>"+
				"                  <KeyDtValue>1967-08-13</KeyDtValue>"+
				"               </KeyDt>"+
				"               <CurCode>AED</CurCode>"+
				"               <AmountDtls>"+
				"                  <AmtType>OutStandingBalance</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>TotalAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>PaymentsAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <AmountDtls>"+
				"                  <AmtType>OverdueAmount</AmtType>"+
				"                  <Amt>0.0</Amt>"+
				"               </AmountDtls>"+
				"               <PaymentMode>0.0</PaymentMode>"+
				"               <WriteoffStat>asd12asd12</WriteoffStat>"+
				"               <WriteoffStatDt>1967-08-13</WriteoffStatDt>"+
				"               <MaxDaysPmtDelay>2</MaxDaysPmtDelay>"+
				"               <MaxDaysPmtDelayDt>1967-08-13</MaxDaysPmtDelayDt>"+
				"               <MonthsOnBook>2</MonthsOnBook>"+
				"               <LastRepmtDt>1967-08-13</LastRepmtDt>"+
				"               <DisputeAlert>a</DisputeAlert>"+
				"               <NonActivePmt>a</NonActivePmt>"+
				"               <IsCurrent>Y</IsCurrent>"+
				"               <ExternalWriteOffCheck>a</ExternalWriteOffCheck>"+
				"               <AECBHistMonthCnt>5</AECBHistMonthCnt>"+
				"            </ServicesDetails>"+
				"         </ProductExposureDetails>"+
				"      </ExposureDetails>"+
				"   </CustomerExposureResponse>"+
				"</EE_EAI_MESSAGE>";

		return response;
}
}
